name: Download

on: push

jobs:
  build_4coder_qol:
    name: Build 4coder_qol
    strategy:
      fail-fast: false
      matrix:
        include:
        - suffix: x64-win
          os: windows-latest
          build_cmd: bin\package.bat -U ..\code\4coder_qol\4coder_qol.cpp code\4coder_qol\custom\bin\buldsuper_
        - suffix: x64-linux
          os: ubuntu-latest
          build_cmd: ./bin/package.sh -U ../code/4coder_qol/4coder_qol.cpp code/4coder_qol/custom/bin/buldsuper_
        - suffix: x64-mac
          os:  macos-15-intel
          build_cmd: ./bin/package.sh -U ../code/4coder_qol/4coder_qol.cpp code/4coder_qol/custom/bin/buldsuper_
    runs-on: ${{ matrix.os }}
    steps:

    - name: checkout 4cc
      uses: actions/checkout@v6
      with:
        repository: 4coder-community/4cc

    - name: checkout 4coder_qol
      uses: actions/checkout@v6
      with:
        path: 4cc/code

    - name: Build 4coder_qol-${{ matrix.suffix }}
    - uses: ilammy/msvc-dev-cmd@v1.4.1  # this is a no-op on Linux and macOS
    - run: |
        cd code
        ${{ matrix.build_cmd }}

    - name: Generate 4coder_qol Artifacts
      uses: actions/upload-artifact@v4.6.0
      with:
        name: 4coder_qol-${{ matrix.suffix }}
        path: |
          custom_4coder.*
          theme-*.4coder

  create_gh_release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build_4coder_qol
    name: Upload
    runs-on: ubuntu-latest
    steps:
    - name: Download 4coder_qol Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts_dir
        pattern: 4coder_qol-*
    - run: |
        cd artifacts_dir
        for f in ./* ; do zip -r "$f.zip" $f ; done;
    - name: Upload Artifacts to Release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts_dir/4coder_qol-*.zip
